services:
  # Основное приложение ArXiv Assistant
  arxiv-assistant:
    build: .
    container_name: arxiv-assistant
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - DOCKER_ENV=true  # Указываем что запущены в Docker
      # OpenAI API ключ (опционально)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      # Предпочтительный провайдер LLM
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
    volumes:
      # Сохраняем загруженные PDF файлы
      - ./uploaded_pdfs:/app/uploaded_pdfs
      # Сохраняем RAG данные
      - ./paper_rag/data:/app/paper_rag/data
      # Сохраняем логи
      - ./logs:/app/logs
    depends_on:
      - ollama
    networks:
      - arxiv-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama сервер для локальных LLM моделей
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_GPU_LAYERS=0
      - OLLAMA_CPU_ONLY=true
      - DOCKER_ENV=true  # Указываем что запущены в Docker
    networks:
      - arxiv-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434/api/tags"]  # Используем имя сервиса
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis для кэширования (опционально)
  redis:
    image: redis:7-alpine
    container_name: arxiv-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - arxiv-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  ollama_data:
    driver: local
  redis_data:
    driver: local

networks:
  arxiv-network:
    driver: bridge
